name: cicd with terraform

on:
  push:
    branches: [main, dev, prod]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4

      - name: create public key file
        run: echo "${{ secrets.EC2_PUBLIC_KEY }}" > terra-key-ec2.pub

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: select or create workspace
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            terraform workspace select default
          else
            terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}
          fi

      - name: terraform plan
        run: terraform plan -var-file="${{ github.ref_name }}.tfvars"

      - name: terraform apply
        run: terraform apply -auto-approve



